/**
 * **The original's texts, per language** — GENERATED, do not edit by hand.
 *
 * The key is the **linear address in the game segment** of the German executable: it is unique, it
 * documents the origin, and it separates lines whose German wording is identical while their
 * translation is not (`' GERUFEN WERDEN'` occurs three times and means three different things). The
 * German wording is the reference our layout tables quote.
 *
 * The other languages are **read from the other executable**, not translated — including the
 * original typos (`SORRYOWLY`, `MININUM`, `PARAPITS`, `FLUMBER`, `UNDESPUTED`, `DEMOLISHEN`), which
 * therefore stay exactly as they are, just like the German `FERITG`.
 *
 * Not in here are texts the original does **not** store as a string (the free-slot placeholder, one
 * half of the copy protection) — those live in `language.ts` under `OPAQUE_TEXTS`.
 *
 * Checked against **both** executables.
 */

/** One original text: address in the German game segment plus the version per language. */
export interface GameTextEntry {
  readonly addr: number;
  readonly de: string;
  readonly en: string;
}

/** Alle 225 Texte, nach Adresse aufsteigend. */
export const GAME_TEXTS: readonly GameTextEntry[] = [
  { addr: 0x4a90, de: 'PROGRAMM UND IDEE:', en: 'PROGRAMMING AND IDEA:' },
  { addr: 0x4aa3, de: 'VOLKER WERTICH', en: 'VOLKER WERTICH' },
  { addr: 0x4ab2, de: 'ALEXANDER JORIAS', en: 'ALEXANDER JORIAS' },
  { addr: 0x4ac3, de: 'INGO FRICK', en: 'INGO FRICK' },
  { addr: 0x4ace, de: 'GRAFIK:', en: 'GRAPHICS:' },
  { addr: 0x4ad6, de: 'CHRISTOPH WERNER', en: 'CHRISTOPH WERNER' },
  { addr: 0x4ae7, de: 'MUSIK UND', en: 'MUSIC AND' },
  { addr: 0x4af1, de: 'SOUNDEFFEKTE:', en: 'SOUNDEFFECTS:' },
  { addr: 0x4aff, de: 'HAIKO RUTTMANN', en: 'HAIKO RUTTMANN' },
  { addr: 0x4b0e, de: 'ONGAME-MUSIK AMIGA:', en: 'ONGAME-MUSIC AMIGA:' },
  { addr: 0x4b22, de: 'MARKUS KLUDZUWEIT', en: 'MARKUS KLUDZUWEIT' },
  { addr: 0x4b34, de: 'PRODUZENT:', en: 'PRODUCER:' },
  { addr: 0x4b3f, de: 'THOMAS HERTZLER', en: 'THOMAS HERTZLER' },
  { addr: 0x4b4f, de: 'ANLEITUNG:', en: 'MANUAL:' },
  { addr: 0x4b5a, de: 'VOLKER WERTICH UND', en: 'VOLKER WERTICH AND' },
  { addr: 0x4b6d, de: 'STEFAN PIASECKI', en: 'STEFAN PIASECKI' },
  { addr: 0x4b7d, de: 'INTRO:', en: 'INTRO:' },
  { addr: 0x4b84, de: 'INGO FRICK', en: 'INGO FRICK' },
  { addr: 0x4b8f, de: 'SPIELETESTER:', en: 'GAME TESTING:' },
  { addr: 0x4b9d, de: 'MATTHIAS BEST', en: 'MATTHIAS BEST' },
  { addr: 0x4bab, de: 'FRANK GRIMM', en: 'FRANK GRIMM' },
  { addr: 0x4bb7, de: 'RALF SCHITTKOWSKI', en: 'RALF SCHITTKOWSKI' },
  { addr: 0x4bc9, de: 'ALEXANDER SPERLING', en: 'ALEXANDER SPERLING' },
  { addr: 0x4bdc, de: 'BIRGIT KRAUSE', en: 'BIRGIT KRAUSE' },
  { addr: 0x4bea, de: 'MICHAEL PASSMANN', en: 'MICHAEL PASSMANN' },
  { addr: 0x4ca8, de: 'PROGRAMMINFO:', en: 'PROGRAM-INFO:' },
  { addr: 0x4cb6, de: 'MISSIONEN: VERFUEGBAR', en: 'MISSIONS:  AVAILABLE' },
  { addr: 0x4ccc, de: 'MISSIONEN: NICHT GENUG SPEICHERPLATZ', en: 'MISSIONS:  NOT ENOUGH RAM AVAILABLE' },
  { addr: 0x4cf1, de: 'SPIELWELT: BIS GROESSE  ', en: 'MAPSIZE:   MAXIMUM IS   ' },
  { addr: 0x4d0a, de: 'BITTE KLICKEN SIE DIE SYMBOLE AN:', en: ' PLEASE IDENTIFY THE SYMBOLS ON' },
  { addr: 0xba6e, de: 'SEITE    ', en: 'PAGE:    ' },
  { addr: 0xba78, de: '      ', en: '      ' },
  { addr: 0x382e4, de: '     ABRISS:', en: '   DEMOLISHEN:' },
  { addr: 0x382f1, de: 'KLICKEN SIE HIER', en: '   CLICK HERE' },
  { addr: 0x38302, de: 'WENN SIE SICHER', en: '   IF YOU ARE' },
  { addr: 0x38312, de: '      SIND', en: '      SURE' },
  { addr: 0x389f2, de: '  GRATULATION', en: 'CONGRATULATIONS.' },
  { addr: 0x38a00, de: 'IHRE FEINDE SIND', en: '  YOUR ENEMIES' },
  { addr: 0x38a11, de: 'CHANCENLOS. SIE', en: '  RESIGN. YOU' },
  { addr: 0x38a21, de: '  HABEN DIESE', en: ' HAVE WON THIS' },
  { addr: 0x38a2f, de: 'MISSION GEWONNEN', en: '    MISSION.' },
  { addr: 0x38a40, de: ' NEUES PASSWORT:', en: '  NEW PASSWORD:' },
  { addr: 0x38a51, de: '--------', en: '--------' },
  { addr: 0x38a5a, de: 'LEIDER HAT SICH', en: 'SORRYOWLY ONE OF' },
  { addr: 0x38a6a, de: '  EINER IHRER', en: 'YOUR ENEMIES HAS' },
  { addr: 0x38a78, de: 'GEGNER IN DIESER', en: '   GAINED THE' },
  { addr: 0x38a89, de: '    MISSION', en: ' SUPERIORITY IN' },
  { addr: 0x38a95, de: ' DURCHGESETZT.', en: '  THIS MISSION' },
  { addr: 0x38aa4, de: '  GUT GEMACHT.', en: '   WELL DONE.' },
  { addr: 0x38ab3, de: ' SIE HABEN IHR', en: ' YOU COMPLETED' },
  { addr: 0x38ac2, de: ' ZIEL IN DIESEM', en: ' THIS TUTORIAL' },
  { addr: 0x38ad2, de: ' TRAININGSSPIEL', en: '     GAME.' },
  { addr: 0x38ae2, de: '   ERREICHT.', en: ' ' },
  { addr: 0x38aef, de: '   DIE BLAUEN', en: '    THE BLUE' },
  { addr: 0x38afd, de: '   DIE ROTEN', en: '    THE RED' },
  { addr: 0x38b0a, de: ' DIE VIOLETTEN', en: '   THE VIOLET' },
  { addr: 0x38b19, de: '   DIE GELBEN', en: '   THE YELLOW' },
  { addr: 0x38b27, de: ' SIEDLER LIEGEN', en: ' SETTLERS HAVE' },
  { addr: 0x38b37, de: ' UNEINHOLBAR IN', en: '   GAINED THE' },
  { addr: 0x38b47, de: '    FUEHRUNG.', en: '  SUPERIORITY' },
  { addr: 0x3916d, de: 'DIE SONNE GEHT AUF UEBER', en: 'THE FIRST RAYS OF THE' },
  { addr: 0x39186, de: 'DEM SIEDLERLAND. SCHON', en: 'SUN GLINT OFF THE' },
  { addr: 0x3919d, de: 'VOR STUNDEN BEGANNEN DIE', en: 'PARAPITS OF YOUR CASTLE.' },
  { addr: 0x391b6, de: 'ERSTEN VOEGEL ZU SINGEN.', en: 'THE DAY BEGINS. THE' },
  { addr: 0x391cf, de: 'BALD WERDEN ALLE IHRE', en: 'BIRDS START TO SING AND' },
  { addr: 0x391e5, de: 'UNTERTANEN WIEDER DEM', en: 'THE SETTLERS RISE FROM' },
  { addr: 0x391fb, de: 'UEBLICHEN TAGEWERK NACH-', en: 'THEIR FLUMBER TO BEGIN' },
  { addr: 0x39214, de: 'GEHEN UND DER LAST, ABER', en: 'ANOTHER DAY OF JOLLY' },
  { addr: 0x3922d, de: 'AUCH DEN KLEINEN FREUDEN', en: 'TOIL.' },
  { addr: 0x39246, de: 'DES ALLTAGS FROEHNEN.', en: ' ' },
  { addr: 0x3925c, de: 'MIT DER SICHEREN GE-', en: 'ALL IS WELL AS YOU' },
  { addr: 0x39271, de: 'WISSHEIT DAS RICH-', en: 'GO TO YOUR WINDOW' },
  { addr: 0x39284, de: 'TIGE ZU TUN SCHIEBEN', en: 'GAZE UPON THE UN-' },
  { addr: 0x39299, de: 'SIE DIE BEINE AUS', en: 'SPOILED COUNTRYSIDE' },
  { addr: 0x392ab, de: 'DEM BETT. SIE LEHNEN', en: 'AND TAKE A LUNG-FULL' },
  { addr: 0x392c0, de: 'SICH AUS DEM FENSTER', en: 'OF PURE COUNTRY AIR.' },
  { addr: 0x392d5, de: 'IN DIE KUEHLE MORGEN-', en: 'FOR TODAY IS THE DAY' },
  { addr: 0x392eb, de: 'LUFT UND ATMEN TIEF', en: 'YOU CAN AT LAST PRO-' },
  { addr: 0x392ff, de: 'DURCH. SIE HABEN ES', en: 'CLAIM YOURSELF BE' },
  { addr: 0x39313, de: 'BEWIESEN: SIE SIND', en: 'UNDESPUTED RULER OF' },
  { addr: 0x39326, de: 'DER HERRSCHER.', en: 'YOUR KINGDOM.' },
  { addr: 0x3a127, de: ' IHRE SIEDLUNG', en: 'YOUR SETTLEMENT' },
  { addr: 0x3a136, de: 'WIRD ANGEGRIFFEN', en: 'IS UNDER ATTACK' },
  { addr: 0x3a147, de: '  IHRE RITTER', en: '  YOUR KNIGHTS' },
  { addr: 0x3a155, de: ' HABEN HIER DEN', en: ' JUST LOST THE' },
  { addr: 0x3a165, de: ' KAMPF VERLOREN', en: '     FIGHT' },
  { addr: 0x3a175, de: 'SIE HABEN EINEN', en: '   YOU GAINED' },
  { addr: 0x3a185, de: ' SIEG ERRUNGEN', en: ' A VICTORY HERE' },
  { addr: 0x3a194, de: 'DIESEM BERGWERK', en: 'THIS MINE HAULS' },
  { addr: 0x3a1a4, de: '   GEHEN DIE', en: '  NO MORE RAW' },
  { addr: 0x3a1b1, de: ' ROHSTOFFE AUS', en: '   MATERIALS' },
  { addr: 0x3a1c0, de: ' EIN RITTER HAT', en: '  A KNIGHT HAS' },
  { addr: 0x3a1d0, de: '   EIN NEUES', en: '  OCCUPIED THIS' },
  { addr: 0x3a1dd, de: 'GEBAEUDE BESETZT', en: '  NEW BUILDING' },
  { addr: 0x3a1ee, de: 'EINE NEUE LAGER-', en: 'A NEW STOCK HAS' },
  { addr: 0x3a1ff, de: 'HALLE IST FERITG', en: '  BEEN BUILT.' },
  { addr: 0x3a210, de: '  DURCH DIESES', en: 'BECAUSE OF THIS' },
  { addr: 0x3a21f, de: ' NEUE FEINDLICHE', en: ' ENEMY BUILDING' },
  { addr: 0x3a230, de: ' GEBAEUDE HABEN', en: '    YOU LOST' },
  { addr: 0x3a240, de: '    SIE LAND', en: '   SOME LAND' },
  { addr: 0x3a24d, de: '  UND GEBAEUDE', en: ' AND BUILDINGS' },
  { addr: 0x3a25c, de: '    VERLOREN', en: ' ' },
  { addr: 0x3a269, de: ' WEGEN ZUWENIG', en: '   EMERGENCY' },
  { addr: 0x3a278, de: 'BAUMATERIAL WIRD', en: '    PROGRAM' },
  { addr: 0x3a289, de: 'DAS NOTPROGRAMM', en: '   ACTIVATED' },
  { addr: 0x3a299, de: '  EINGELEITET', en: ' ' },
  { addr: 0x3a2a7, de: 'DAS NOTPROGRAMM', en: '   EMERGENCY' },
  { addr: 0x3a2b7, de: '  WIRD WIEDER', en: '    PROGRAM' },
  { addr: 0x3a2c5, de: '   ABGESETZT', en: '  NEUTRALIZED' },
  { addr: 0x3a2d2, de: 'EIN GEOLOGE HAT', en: '   A GEOLOGIST' },
  { addr: 0x3a2e2, de: ' GOLD GEFUNDEN', en: ' HAS FOUND GOLD' },
  { addr: 0x3a2f1, de: ' EISEN GEFUNDEN', en: ' HAS FOUND IRON' },
  { addr: 0x3a301, de: ' KOHLE GEFUNDEN', en: ' HAS FOUND COAL' },
  { addr: 0x3a311, de: 'GRANIT GEFUNDEN', en: 'HAS FOUND STONES' },
  { addr: 0x3a321, de: ' SIE WOLLTEN AN', en: ' YOU WANTED ME' },
  { addr: 0x3a331, de: '  DIESE STELLE', en: ' TO CALL YOU TO' },
  { addr: 0x3a340, de: ' GERUFEN WERDEN', en: ' THIS LOCATION' },
  { addr: 0x3a350, de: ' SIE WOLLTEN ZU', en: ' YOU WANTED ME' },
  { addr: 0x3a360, de: '  DIESEM MENU', en: ' TO CALL YOU TO' },
  { addr: 0x3a36e, de: ' GERUFEN WERDEN', en: '   THIS MENU' },
  { addr: 0x3a37e, de: ' SIE HABEN VOR', en: ' ' },
  { addr: 0x3a38d, de: '   30 MINUTEN', en: ' 30 MIN. PASSED' },
  { addr: 0x3a39b, de: '  EINER STUNDE', en: 'ONE HOUR PASSED' },
  { addr: 0x3a3aa, de: ' DAS LETZTE MAL', en: ' SINCE THE LAST' },
  { addr: 0x3a3ba, de: '  GESPEICHERT', en: '     SAVING.' },
  { addr: 0x3a3c8, de: 'ZU DIESEM LAGER', en: ' TO CALL YOU TO' },
  { addr: 0x3a3d8, de: ' GERUFEN WERDEN', en: '   THIS STOCK' },
  { addr: 0x3a9ec, de: 'ERFOLGSQUOTE', en: 'MINING' },
  { addr: 0x3a9f9, de: 'DES BERGWERKS:', en: 'OUTPUT:' },
  { addr: 0x3aa08, de: '%', en: '%' },
  { addr: 0x3ab35, de: 'AUFTRAG DER', en: 'ORDERED' },
  { addr: 0x3ab41, de: 'BAUSTELLE:', en: 'BUILDING:' },
  { addr: 0x3af2b, de: 'LAGERBESTAND', en: 'STOCK OF' },
  { addr: 0x3af38, de: 'DES GEBAEUDES:', en: 'THIS BUILDING:' },
  { addr: 0x3b208, de: 'BESETZUNG:', en: 'DEFENDERS:' },
  { addr: 0x3b3d6, de: 'WARENTRANSPORT:', en: 'TRANSPORT INFO:' },
  { addr: 0x3b5ca, de: 'JOYSTICK', en: 'JOYSTICK' },
  { addr: 0x3b5d3, de: 'MAUS  MODUS:', en: 'MOUSE MODUS:' },
  { addr: 0x3b5e0, de: 'MICROSOFT', en: 'MICROSOFT' },
  { addr: 0x3b5ea, de: 'MOUSESYSTEMS', en: 'MOUSESYSTEMS' },
  { addr: 0x3b5f7, de: 'GESCHWIND.', en: 'JOYSPEED:' },
  { addr: 0x3b602, de: 'TOLERANZ:', en: 'TOLERANCE:' },
  { addr: 0x3b60c, de: 'COM-PORT', en: 'COM-PORT' },
  { addr: 0x3b615, de: 'IRQ-NUMMER', en: 'IRQ-NUMBER' },
  { addr: 0x3bcd2, de: '  WEGEBAU-', en: '  PATHWAY- ' },
  { addr: 0x3bcdd, de: ' SCROLLING', en: ' SCROLLING ' },
  { addr: 0x3bce8, de: ' SCHNELLER', en: '    FAST   ' },
  { addr: 0x3bcf3, de: 'KARTENKLICK', en: '  MAPCLICK ' },
  { addr: 0x3bcff, de: ' SCHNELLER', en: '    FAST   ' },
  { addr: 0x3bd0a, de: '  BAUKLICK', en: '  BUILDING ' },
  { addr: 0x3bd15, de: 'LINKE     RECHTE', en: 'LEFT       RIGHT' },
  { addr: 0x3bd26, de: 'SEITE      SEITE', en: 'SIDE        SIDE' },
  { addr: 0x3bd37, de: '  MITTEILUNGEN  ', en: '    MESSAGES    ' },
  { addr: 0x3bd48, de: 'MUSIK', en: 'MUSIC' },
  { addr: 0x3bd4e, de: '  SVGA', en: '  SVGA' },
  { addr: 0x3bd55, de: '  MODE', en: '  MODE' },
  { addr: 0x3bd5c, de: ' LAUT-', en: ' ' },
  { addr: 0x3bd63, de: 'STAERKE:', en: ' VOLUME:' },
  { addr: 0x3bede, de: '   WOLLEN SIE', en: '   DO YOU WANT' },
  { addr: 0x3beec, de: '  DIESES SPIEL', en: '    TO QUIT' },
  { addr: 0x3befb, de: '   BEENDEN ?', en: '   THIS GAME ?' },
  { addr: 0x3bf08, de: '  JA       NEIN', en: '  YES       NO' },
  { addr: 0x3bf18, de: '  DER AKTUELLE', en: 'THE GAME HAS NOT' },
  { addr: 0x3bf27, de: '   SPIELSTAND', en: '   BEEN SAVED' },
  { addr: 0x3bf35, de: '  WURDE NICHT', en: '   RECENTLY.' },
  { addr: 0x3bf43, de: 'GESPEICHERT.SIND', en: '    ARE YOU' },
  { addr: 0x3bf54, de: '  SIE SICHER ?', en: '     SURE ?' },
  { addr: 0x3c0ec, de: '    JOYSTICK', en: '   CALIBRATE' },
  { addr: 0x3c0f9, de: '  KALIBRIEREN:', en: '   JOYSTICK:' },
  { addr: 0x3c108, de: 'BEWEGEN SIE DEN', en: ' ' },
  { addr: 0x3c118, de: 'JOYSTICK IN DIE', en: ' MOVE THE STICK' },
  { addr: 0x3c128, de: '   ANGEGEBENE', en: '  AS TOLD BELOW' },
  { addr: 0x3c136, de: '  RICHTUNG UND', en: ' AND PRESS FIRE.' },
  { addr: 0x3c145, de: 'DRUECKEN SIE DEN', en: ' ' },
  { addr: 0x3c156, de: '   FEUERKNOPF.', en: ' ' },
  { addr: 0x3c165, de: '     MITTE', en: '     CENTER' },
  { addr: 0x3c170, de: '   OBEN LINKS', en: '     UP LEFT' },
  { addr: 0x3c17e, de: '  UNTEN RECHTS', en: '    DOWN RIGHT' },
  { addr: 0x3c18d, de: '     MITTE', en: '     CENTER' },
  { addr: 0x3c624, de: 'MINIMUM', en: 'MININUM' },
  { addr: 0x3c62c, de: 'SCHWACH', en: 'WEAK' },
  { addr: 0x3c634, de: 'MITTEL', en: 'MEDIUM' },
  { addr: 0x3c63b, de: 'GUT', en: 'GOOD' },
  { addr: 0x3c63f, de: 'VOLL', en: 'FULL' },
  { addr: 0x3ec1c, de: '  BODENPROBEN:', en: 'GROUND-ANALYSIS:' },
  { addr: 0x3ec2b, de: 'UNAUFFINDBAR', en: 'NOT PRESENT' },
  { addr: 0x3ec38, de: 'MINIMAL', en: 'MINIMUM' },
  { addr: 0x3ec40, de: 'SEHR WENIG', en: 'VERY FEW' },
  { addr: 0x3ec4b, de: 'WENIG', en: 'FEW' },
  { addr: 0x3ec51, de: 'UNTER MITTEL', en: 'BELOW AVERAGE' },
  { addr: 0x3ec5e, de: 'DURCHSCHNITT', en: 'AVERAGE' },
  { addr: 0x3ec6b, de: 'UEBER MITTEL', en: 'ABOVE AVERAGE' },
  { addr: 0x3ec78, de: 'VIEL', en: 'MUCH' },
  { addr: 0x3ec7d, de: 'SEHR VIEL', en: 'VERY MUCH' },
  { addr: 0x3ec87, de: 'EXTREM VIEL', en: 'PERFECT' },
  { addr: 0x3ed72, de: 'LADE ARCHIV...', en: 'LOADING ARCHIVE.' },
  { addr: 0x3ee94, de: 'SPIEL SPEICHERN:', en: '   SAVE  GAME   ' },
  { addr: 0x3eea5, de: 'SPIEL LADEN:    ', en: '   LOAD  GAME   ' },
  { addr: 0x3f376, de: 'DISKMELDUNG:', en: 'DISK MESSAGE:' },
  { addr: 0x3f383, de: 'SPIELSTAND', en: 'GAME' },
  { addr: 0x3f38e, de: 'GESPEICHERT.', en: 'SAVED.' },
  { addr: 0x3f39b, de: 'GELADEN.', en: 'LOADED.' },
  { addr: 0x3f3a4, de: 'FEHLERMELDUNG:', en: 'ERROR:' },
  { addr: 0x3f3b3, de: 'KANN KEIN ARCHIV', en: 'UNABLE TO SAVE' },
  { addr: 0x3f3c4, de: 'ANLEGEN.', en: 'ARCHIVE.' },
  { addr: 0x3f3cd, de: 'KANN DATEI NICHT', en: 'UNABLE TO OPEN' },
  { addr: 0x3f3de, de: 'OEFFNEN.', en: 'FILE.' },
  { addr: 0x3f3e7, de: 'DISK VOLL ODER', en: 'DISK FULL OR' },
  { addr: 0x3f3f6, de: 'SCHREIBFEHLER.', en: 'WRITE ERROR.' },
  { addr: 0x3f405, de: 'LESEFEHLER.', en: 'READ ERROR.' },
  { addr: 0x3f411, de: 'KONFIGURATION', en: 'INVALID' },
  { addr: 0x3f41f, de: 'UNZULAESSIG.', en: 'CONFIGURATION.' },
  { addr: 0x3f95c, de: '    ', en: '    ' },
  { addr: 0x41bfb, de: '%', en: '%' },
  { addr: 0x4eb82, de: '--------', en: '--------' },
  { addr: 0x4f118, de: 'MISSION: --.LEVEL', en: 'MISSION: --.LEVEL' },
  { addr: 0x4f12a, de: 'PASSWORT:', en: 'PASSWORD:' },
  { addr: 0x4f134, de: 'TRAININGSSPIEL:', en: 'TUTORIAL GAME:' },
  { addr: 0x4f144, de: '--. LEVEL', en: '--. LEVEL' },
  { addr: 0x4f14e, de: '1 SPIELER', en: '1 PLAYER' },
  { addr: 0x4f158, de: '2 SPIELER', en: '2 PLAYERS' },
  { addr: 0x4f162, de: 'DEMO', en: 'DEMO' },
  { addr: 0x4f167, de: 'KARTEN-', en: ' ' },
  { addr: 0x4f16f, de: 'GROESSE:-', en: 'MAPSIZE:-' },
  { addr: 0x60a2a, de: 'BBDDFFHHVTTTTTT', en: 'BBDDFFHHVTTTTTT' },
];
